spring:
  application:
    name: learn-spring-ai


  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.4-2026-03-05
          temperature: 0.9

logging:
  level:
    org.springframework.ai.chat.client: DEBUG