spring:
  application:
    name: learn-spring-ai

  datasource:
    url: jdbc:postgresql://localhost:5422/spring-ai
    username: postgres
    password: Li@180803
    driver-class-name: org.postgresql.Driver


  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.4-2026-03-05
          temperature: 0.9
    vectorstore:
      pgvector:
        initialize-schema: true
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            table-name: chat_memory

logging:
  level:
    org.springframework.ai.chat.client: DEBUG